# Generated by Django 5.0.6 on 2024-06-08 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productName', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('rating', models.DecimalField(decimal_places=1, max_digits=3)),
                ('discount', models.IntegerField()),
                ('availability', models.CharField(choices=[('yes', 'yes'), ('oou-of-stock', 'out-of-stock')], max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='company',
            name='code',
            field=models.CharField(max_length=3, unique=True),
        ),
    ]
