# Generated by Django 5.0.6 on 2024-06-08 05:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0006_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(default="laptop" ,on_delete=django.db.models.deletion.CASCADE, to='company.category'),
            preserve_default=False,
        ),
    ]
